# Generated by Django 3.1.1 on 2020-09-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesdetails',
            name='datetime',
            field=models.DateField(),
        ),
    ]
