# Generated by Django 3.1.1 on 2020-09-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsk', '0002_auto_20200907_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesdetails',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
