# Generated by Django 3.0.8 on 2020-09-08 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsk', '0003_auto_20200907_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
