# Generated by Django 3.1.1 on 2020-09-08 06:42

from django.db import migrations, models
import rsk.models


class Migration(migrations.Migration):

    dependencies = [
        ('rsk', '0004_auto_20200908_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[rsk.models.validate_name]),
        ),
    ]
