# Generated by Django 3.1.1 on 2020-09-20 10:45

from django.db import migrations, models
import rsk.models


class Migration(migrations.Migration):

    dependencies = [
        ('rsk', '0005_auto_20200908_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[rsk.models.validate_name])),
                ('image', models.ImageField(upload_to='%Y/%m/%d')),
            ],
        ),
    ]
